#!/usr/bin/env python3

import subprocess

files = subprocess.check_output("find build/tmp/ -type f -name 'default_*'", shell=True).decode("utf-8").split('\n')[:-1]
for path in files:
	print(path.split('/')[-1] + ":")
	print("START           |END             |SIZE (B)  |SIZE(KB)  |TYPE|NAME")
	nms = subprocess.check_output("nm --print-size --size-sort " + path, shell=True).decode("utf-8").split('\n')[:-1]
	for obj in nms:
		start, end, type, name = obj.split(' ')
		start = int(start, base=16)
		end = int(end, base=16)
		size = end - start
		
		print("%016X|%016X|%10i|%10.2f|%4s|%s" % (start, end, size, size / 1024.0, type, name))
